from src.models import Category

# 28 products: 17 In Stock (stock > 10), 7 Low Stock (1-10), 4 Out of Stock (0)
SEED_PRODUCTS: list[dict] = [
    # Electronics — 8 products (5 In Stock, 2 Low Stock, 1 Out of Stock)
    {
        "name": "Mechanical Keyboard",
        "category": Category.ELECTRONICS,
        "price": 149.99,
        "stock": 45,
        "sku": "ELEC-001",
    },
    {
        "name": '27" 4K Monitor',
        "category": Category.ELECTRONICS,
        "price": 449.99,
        "stock": 23,
        "sku": "ELEC-002",
    },
    {
        "name": "Wireless Mouse",
        "category": Category.ELECTRONICS,
        "price": 79.99,
        "stock": 67,
        "sku": "ELEC-003",
    },
    {
        "name": "USB-C Hub",
        "category": Category.ELECTRONICS,
        "price": 59.99,
        "stock": 34,
        "sku": "ELEC-004",
    },
    {
        "name": "Webcam HD Pro",
        "category": Category.ELECTRONICS,
        "price": 129.99,
        "stock": 12,
        "sku": "ELEC-005",
    },
    {
        "name": "Noise-Canceling Headphones",
        "category": Category.ELECTRONICS,
        "price": 299.99,
        "stock": 8,
        "sku": "ELEC-006",
    },
    {
        "name": "Portable Speaker",
        "category": Category.ELECTRONICS,
        "price": 89.99,
        "stock": 3,
        "sku": "ELEC-007",
    },
    {
        "name": "VR Headset",
        "category": Category.ELECTRONICS,
        "price": 499.99,
        "stock": 0,
        "sku": "ELEC-008",
    },
    # Software — 7 products (4 In Stock, 2 Low Stock, 1 Out of Stock)
    {
        "name": "IDE Pro License",
        "category": Category.SOFTWARE,
        "price": 199.99,
        "stock": 500,
        "sku": "SOFT-001",
    },
    {
        "name": "Cloud Storage Plan",
        "category": Category.SOFTWARE,
        "price": 9.99,
        "stock": 999,
        "sku": "SOFT-002",
    },
    {
        "name": "Design Suite License",
        "category": Category.SOFTWARE,
        "price": 349.99,
        "stock": 150,
        "sku": "SOFT-003",
    },
    {
        "name": "Project Management Tool",
        "category": Category.SOFTWARE,
        "price": 14.99,
        "stock": 200,
        "sku": "SOFT-004",
    },
    {
        "name": "VPN Annual Subscription",
        "category": Category.SOFTWARE,
        "price": 49.99,
        "stock": 5,
        "sku": "SOFT-005",
    },
    {
        "name": "Antivirus Premium",
        "category": Category.SOFTWARE,
        "price": 39.99,
        "stock": 7,
        "sku": "SOFT-006",
    },
    {
        "name": "Video Editor Pro",
        "category": Category.SOFTWARE,
        "price": 299.99,
        "stock": 0,
        "sku": "SOFT-007",
    },
    # Hardware — 7 products (5 In Stock, 1 Low Stock, 1 Out of Stock)
    {
        "name": "1TB NVMe SSD",
        "category": Category.HARDWARE,
        "price": 109.99,
        "stock": 56,
        "sku": "HDWR-001",
    },
    {
        "name": "32GB DDR5 RAM Kit",
        "category": Category.HARDWARE,
        "price": 189.99,
        "stock": 28,
        "sku": "HDWR-002",
    },
    {
        "name": "750W Power Supply",
        "category": Category.HARDWARE,
        "price": 119.99,
        "stock": 19,
        "sku": "HDWR-003",
    },
    {
        "name": "CPU Cooler Tower",
        "category": Category.HARDWARE,
        "price": 69.99,
        "stock": 41,
        "sku": "HDWR-004",
    },
    {
        "name": "ATX Mid-Tower Case",
        "category": Category.HARDWARE,
        "price": 99.99,
        "stock": 15,
        "sku": "HDWR-005",
    },
    {
        "name": "GPU Riser Cable",
        "category": Category.HARDWARE,
        "price": 29.99,
        "stock": 2,
        "sku": "HDWR-006",
    },
    {
        "name": "Thunderbolt 4 Dock",
        "category": Category.HARDWARE,
        "price": 279.99,
        "stock": 0,
        "sku": "HDWR-007",
    },
    # Accessories — 6 products (3 In Stock, 2 Low Stock, 1 Out of Stock)
    {
        "name": "Laptop Stand",
        "category": Category.ACCESSORIES,
        "price": 49.99,
        "stock": 82,
        "sku": "ACCS-001",
    },
    {
        "name": "Desk Mat XXL",
        "category": Category.ACCESSORIES,
        "price": 34.99,
        "stock": 63,
        "sku": "ACCS-002",
    },
    {
        "name": "Cable Management Kit",
        "category": Category.ACCESSORIES,
        "price": 24.99,
        "stock": 45,
        "sku": "ACCS-003",
    },
    {
        "name": "Monitor Light Bar",
        "category": Category.ACCESSORIES,
        "price": 59.99,
        "stock": 9,
        "sku": "ACCS-004",
    },
    {
        "name": "Ergonomic Wrist Rest",
        "category": Category.ACCESSORIES,
        "price": 19.99,
        "stock": 4,
        "sku": "ACCS-005",
    },
    {
        "name": "Webcam Privacy Cover",
        "category": Category.ACCESSORIES,
        "price": 9.99,
        "stock": 0,
        "sku": "ACCS-006",
    },
]
